### ISSUE TITLE
Updates des Abschnitts-Titels erzeugt Fehler

### ISSUE THREAD

**Issue by relecand** [sudile/moodle-format_tabtopics#7]
Moodle 3.1+ (Build: 20160623)
Themes: Essential und Clean

Reproduktion:
1. Kurs auf Tabtopics umstellen
2. Abschnitts-Titel umbenennen > Fehler
3. Kurs auf Topics-Format umstellen
4. Abschnitts-Titel umbenennen > kein Fehler

![screenshot-2016-06-28-21-31-25](https://cloud.githubusercontent.com/assets/5286499/16429668/4de57a00-3d78-11e6-8a4a-ed0d5dae7f71.jpg)

**Comment by jojoob** [comment]
Das Problem tritt in Moodle 3.1 wegen einer API Änderung auf.

Mit Commit 741f947e3f199e6b3cf50988c105a0ff449dfbe0 behoben.
